name: run main.py

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *' # *:00に実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: |
          python main.py >> $GITHUB_ENV

      - name: commit files
        if: ${{ env.isChanged == 'True' }}
        run: |
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git diff-index --quiet HEAD || (git commit -a -m "Update files")

      - name: push changes
        if: ${{ env.isChanged == 'True' }}
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
